# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui',
# licensing of 'design.ui' applies.
#
# Created: Fri Jul 26 11:46:44 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1139, 975)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 211, 811))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LTitreAcademie = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.LTitreAcademie.setObjectName("LTitreAcademie")
        self.verticalLayout.addWidget(self.LTitreAcademie)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PBNomEtablissement = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PBNomEtablissement.setObjectName("PBNomEtablissement")
        self.horizontalLayout_3.addWidget(self.PBNomEtablissement)
        self.LNom = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.LNom.setObjectName("LNom")
        self.horizontalLayout_3.addWidget(self.LNom)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.PBAdresseEtablissement = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PBAdresseEtablissement.setObjectName("PBAdresseEtablissement")
        self.horizontalLayout_9.addWidget(self.PBAdresseEtablissement)
        self.LAdresseEtablissement = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.LAdresseEtablissement.setObjectName("LAdresseEtablissement")
        self.horizontalLayout_9.addWidget(self.LAdresseEtablissement)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.LTitreClasse = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.LTitreClasse.setObjectName("LTitreClasse")
        self.verticalLayout.addWidget(self.LTitreClasse)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.PBNomClasse = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PBNomClasse.setObjectName("PBNomClasse")
        self.horizontalLayout_8.addWidget(self.PBNomClasse)
        self.LNomClasse = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.LNomClasse.setObjectName("LNomClasse")
        self.horizontalLayout_8.addWidget(self.LNomClasse)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.CBAnneeScolaire = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.CBAnneeScolaire.setObjectName("CBAnneeScolaire")
        self.horizontalLayout_7.addWidget(self.CBAnneeScolaire)
        self.lAnneeScolaire = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lAnneeScolaire.setObjectName("lAnneeScolaire")
        self.horizontalLayout_7.addWidget(self.lAnneeScolaire)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CBAnneeScolaire_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.CBAnneeScolaire_2.setObjectName("CBAnneeScolaire_2")
        self.horizontalLayout_5.addWidget(self.CBAnneeScolaire_2)
        self.ProfPrincipal = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ProfPrincipal.setObjectName("ProfPrincipal")
        self.horizontalLayout_5.addWidget(self.ProfPrincipal)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.LTitreEleve = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.LTitreEleve.setObjectName("LTitreEleve")
        self.verticalLayout.addWidget(self.LTitreEleve)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LENomEleve = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LENomEleve.setObjectName("LENomEleve")
        self.horizontalLayout.addWidget(self.LENomEleve)
        self.LNomEleve = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.LNomEleve.setObjectName("LNomEleve")
        self.horizontalLayout.addWidget(self.LNomEleve)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LEPrenomEleve = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LEPrenomEleve.setObjectName("LEPrenomEleve")
        self.horizontalLayout_2.addWidget(self.LEPrenomEleve)
        self.LPrenomEleve = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.LPrenomEleve.setObjectName("LPrenomEleve")
        self.horizontalLayout_2.addWidget(self.LPrenomEleve)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.PBAdresse = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PBAdresse.setObjectName("PBAdresse")
        self.horizontalLayout_10.addWidget(self.PBAdresse)
        self.LAdresse = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.LAdresse.setObjectName("LAdresse")
        self.horizontalLayout_10.addWidget(self.LAdresse)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(600, 740, 511, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_6.setObjectName("pushButton_6")
0
1
2
3
4
5
6
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(220, 20, 881, 711))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LBulletinEleve = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.LBulletinEleve.setObjectName("LBulletinEleve")
        self.verticalLayout_3.addWidget(self.LBulletinEleve)
        self.TWEleve = QtWidgets.QTableWidget(self.horizontalLayoutWidget_12)
        self.TWEleve.setLineWidth(1)
        self.TWEleve.setAutoScroll(True)
        self.TWEleve.setObjectName("TWEleve")
        self.TWEleve.setColumnCount(7)
        self.TWEleve.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TWEleve.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWEleve.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWEleve.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWEleve.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWEleve.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWEleve.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWEleve.setHorizontalHeaderItem(6, item)
        self.verticalLayout_3.addWidget(self.TWEleve)
        self.horizontalLayout_12.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.LTitreRepresentationGraphique = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LTitreRepresentationGraphique.sizePolicy().hasHeightForWidth())
        self.LTitreRepresentationGraphique.setSizePolicy(sizePolicy)
        self.LTitreRepresentationGraphique.setObjectName("LTitreRepresentationGraphique")
        self.verticalLayout_4.addWidget(self.LTitreRepresentationGraphique)
        self.LRepresentationGraphique = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LRepresentationGraphique.sizePolicy().hasHeightForWidth())
        self.LRepresentationGraphique.setSizePolicy(sizePolicy)
        self.LRepresentationGraphique.setObjectName("LRepresentationGraphique")
        self.verticalLayout_4.addWidget(self.LRepresentationGraphique)
        self.horizontalLayout_12.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1139, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.LTitreAcademie.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.PBNomEtablissement.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.LNom.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.PBAdresseEtablissement.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.LAdresseEtablissement.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.LTitreClasse.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.PBNomClasse.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.LNomClasse.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.lAnneeScolaire.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.ProfPrincipal.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.LTitreEleve.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.LNomEleve.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.LPrenomEleve.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.PBAdresse.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.LAdresse.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.pushButton_6.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.LBulletinEleve.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.TWEleve.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Nom", None, -1))
        self.TWEleve.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Prenom", None, -1))
        self.TWEleve.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Matieres", None, -1))
        self.TWEleve.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Note", None, -1))
        self.TWEleve.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Moyenneclasse", None, -1))
        self.TWEleve.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "Moyenne élève", None, -1))
        self.TWEleve.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("MainWindow", "Appréciation", None, -1))
        self.LTitreRepresentationGraphique.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.LRepresentationGraphique.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))

